"""Imbalanced CIC sensitivity under the locked publication configuration."""
from __future__ import annotations
import argparse, json, sys, time
from pathlib import Path
import numpy as np, pandas as pd
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.feature_selection import chi2
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report, confusion_matrix
if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src.experiment_components import WeightedRandomForest, compute_metrics

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--processed-dir',type=Path,required=True); ap.add_argument('--output-dir',type=Path,required=True); ap.add_argument('--chi2-k',type=int,default=60); ap.add_argument('--n-estimators',type=int,default=100); ap.add_argument('--min-samples-leaf',type=int,default=2); ap.add_argument('--seeds',type=int,nargs='+',default=[42,2024,3407]); a=ap.parse_args(); a.output_dir.mkdir(parents=True,exist_ok=True)
    tr=pd.read_csv(a.processed_dir/'train.csv',low_memory=False); va=pd.read_csv(a.processed_dir/'validation.csv',low_memory=False); te=pd.read_csv(a.processed_dir/'test.csv',low_memory=False); names=[c for c in tr.columns if c!='target']; sc=MinMaxScaler(); X=sc.fit_transform(tr[names].apply(pd.to_numeric,errors='raise')); Xv=sc.transform(va[names].apply(pd.to_numeric,errors='raise')); Xt=sc.transform(te[names].apply(pd.to_numeric,errors='raise')); y=tr.target.to_numpy(); yv=va.target.to_numpy(); yt=te.target.to_numpy(); scores,_=chi2(X,y); idx=np.argsort(-np.nan_to_num(scores,nan=0.0,posinf=np.finfo(float).max))[:a.chi2_k]; labels=sorted(np.unique(np.concatenate([y,yt]))); rows=[]
    for seed in a.seeds:
      models={'random_forest_all':(RandomForestClassifier(n_estimators=a.n_estimators,min_samples_leaf=a.min_samples_leaf,n_jobs=-1,class_weight='balanced_subsample',random_state=seed),np.arange(X.shape[1])), 'random_forest_chi2':(RandomForestClassifier(n_estimators=a.n_estimators,min_samples_leaf=a.min_samples_leaf,n_jobs=-1,class_weight='balanced_subsample',random_state=seed),idx), 'extra_trees_chi2':(ExtraTreesClassifier(n_estimators=a.n_estimators,min_samples_leaf=a.min_samples_leaf,n_jobs=-1,class_weight='balanced',random_state=seed),idx)}
      for name,(m,cols) in models.items():
        s=time.perf_counter(); m.fit(X[:,cols],y); ts=time.perf_counter()-s; s=time.perf_counter(); p=m.predict(Xt[:,cols]); ps=time.perf_counter()-s; rows.append({'model':name,'seed':seed,**compute_metrics(yt,p),'train_seconds':ts,'predict_seconds':ps,'feature_count':len(cols),'test_samples':len(yt)}); pd.DataFrame({'y_true':yt,'y_pred':p}).to_csv(a.output_dir/f'predictions_{name}_seed{seed}.csv',index=False,encoding='utf-8-sig'); pd.DataFrame(classification_report(yt,p,labels=labels,output_dict=True,zero_division=0)).T.to_csv(a.output_dir/f'classification_report_{name}_seed{seed}.csv',encoding='utf-8-sig'); pd.DataFrame(confusion_matrix(yt,p,labels=labels),index=labels,columns=labels).to_csv(a.output_dir/f'confusion_matrix_{name}_seed{seed}.csv',encoding='utf-8-sig')
      w=WeightedRandomForest(n_estimators=a.n_estimators,min_samples_leaf=a.min_samples_leaf,random_state=seed,weight_metric='balanced_accuracy'); s=time.perf_counter(); w.fit(X[:,idx],y,Xv[:,idx],yv); ts=time.perf_counter()-s; s=time.perf_counter(); p=w.predict(Xt[:,idx]); ps=time.perf_counter()-s; rows.append({'model':'weighted_rf_chi2','seed':seed,**compute_metrics(yt,p),'train_seconds':ts,'predict_seconds':ps,'feature_count':len(idx),'test_samples':len(yt)}); pd.DataFrame({'y_true':yt,'y_pred':p}).to_csv(a.output_dir/f'predictions_weighted_rf_chi2_seed{seed}.csv',index=False,encoding='utf-8-sig'); pd.DataFrame(classification_report(yt,p,labels=labels,output_dict=True,zero_division=0)).T.to_csv(a.output_dir/f'classification_report_weighted_rf_chi2_seed{seed}.csv',encoding='utf-8-sig'); pd.DataFrame(confusion_matrix(yt,p,labels=labels),index=labels,columns=labels).to_csv(a.output_dir/f'confusion_matrix_weighted_rf_chi2_seed{seed}.csv',encoding='utf-8-sig'); pd.DataFrame({'tree_score':w.tree_scores_,'tree_weight':w.tree_weights_}).to_csv(a.output_dir/f'tree_weights_seed{seed}.csv',index=False,encoding='utf-8-sig')
    result=pd.DataFrame(rows); result.to_csv(a.output_dir/'metrics_3seeds.csv',index=False,encoding='utf-8-sig'); result.groupby('model')[['accuracy','balanced_accuracy','macro_precision','macro_recall','macro_f1','train_seconds','predict_seconds']].agg(['mean','std']).reset_index().to_csv(a.output_dir/'metrics_aggregate.csv',index=False,encoding='utf-8-sig'); (a.output_dir/'config.json').write_text(json.dumps({'chi2_k':a.chi2_k,'n_estimators':a.n_estimators,'min_samples_leaf':a.min_samples_leaf,'seeds':a.seeds},ensure_ascii=False,indent=2),encoding='utf-8'); print(result.to_string(index=False))
if __name__=='__main__': main()
