"""Rewrite logs/review_round_counter.txt from explicit fields.

The counter is local state (logs/ is gitignored) but it is the only record of
which rotation item each review round covered, so it has to stay readable and
correct.  Editing it through a script avoids the long single-line note drifting
out of sync with the header.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
ROOT = Path(__file__).resolve().parents[1]
COUNTER = ROOT / "logs" / "review_round_counter.txt"

FIELDS = {
    "round": "37",
    "last_item": "37",
    "last_item_title": "Provenance and verification for each of the five equations",
    "last_result": "fixed",
    "note": ("wrote 公式来源与核验.md/.docx: what each numbered equation is, where it comes from "
             "and whether the numbers printed beside it reproduce.  Equation (1) is the paper's own "
             "mechanism specification (a weighted average of posteriors, the family Breiman's "
             "averaging belongs to, with the literature's variants listed in Section 2 and "
             "temperature scaling and Mondrian conformal prediction cited as the steps after it); "
             "Equation (2) is derived here from the triangle inequality and the experts' standing on "
             "the simplex, and its coverage reproduces (99.91% of rows provably immune, "
             "margin-to-bound ratio 3,469-5,038, zero labels changed); Equations (3) and (4) are "
             "second- and first-order expansions rather than identities, which the text says, and "
             "their four printed numbers all reproduce from the released per-row file: observed "
             "entropy deficiency 3.237e-05 against 3.187e-05 predicted (1.5%) and 3.365e-05 (4.0%), "
             "with a median risk-offset standard deviation of 0.000220; Equation (5) is the standard "
             "normalised Shannon entropy, with the measured weight entropy 0.99998. "
             "scripts/build_equation_sources_doc_v1.py verifies all of it and joins the gate in "
             "--check mode (48 checks), so a printed value that stops matching its artefact fails "
             "the gate without rewriting the deliverable. The document ships in 07_复现材料. "
             "PREVIOUS: the author pointed out that the first sources document covered only the evaluation "
             "datasets, and it did. 数据与资料来源总表.md/.docx replaces it with nine sections: the "
             "four evaluation datasets with URL/date/snapshot/licence/checksum and their role; the "
             "per-file verification of eight CIC-IDS2017 CSVs plus five other files, digests "
             "recomputed at build time (all 13 verify, and the CIC rows sum to 2 830 743 = the "
             "audit's source_rows); the six derived populations with split sizes; the software and "
             "runtime that produced the numbers (12 direct dependencies, 117 locked packages, "
             "python:3.11-slim, the CI runner, CICFlowMeter upstream, unrar 7.30 for the N-BaIoT "
             "RARs); the literature (47 references, 36 DOIs verified through Crossref/DataCite, 11 "
             "no-DOI venues, with the per-entry record); the journal requirements the format "
             "follows, with the documents that record them; this project's own release archives "
             "with their checksums; the 77 files deliberately moved out of the release in two "
             "quarantine passes; and the verification method with its limits.  Building it exposed "
             "two gaps it then closed: python-pptx (needed by the deck builder) was missing from "
             "the dependency list, and the retired 数据来源总表 pair is now moved to "
             ".quarantine/superseded_docs/ rather than deleted. "
             "PREVIOUS: compiled 数据来源总表.md/.docx: the provenance that lived in three places (S01's "
             "provenance table, the per-file checksum list and the processed-data audits) is now "
             "one document. It carries the four raw sources with URL, retrieval date, snapshot, "
             "licence and checksum; a per-file table for the eight CIC-IDS2017 CSVs and the other "
             "five files with rows, bytes and digest verification recomputed at build time; the "
             "six derived populations with their split sizes and build scripts; the retrieval "
             "evidence under docs/source_records/; and the verification method with its honest "
             "limits (files that are not kept locally are marked as such rather than inferred). "
             "The first build mis-parsed the recorded digests - the provenance cell reads "
             "'KDDTrain+ SHA-256=…' so a startswith test found nothing and every external file "
             "was reported as mismatching - and printed a line count for the N-BaIoT archive; "
             "both fixed. All 13 recorded digests now verify, and the eight CIC files sum to "
             "2 830 743 rows, the audit's source_rows. The document ships in 07_复现材料 and is "
             "built by build_restructured_manuscript_v4.py --only sources. "
             "PREVIOUS: built 汇报用_论文介绍.pptx: eight 16:9 slides following the talk script - thesis and "
             "three key numbers, the four contamination sources, the six-stage protocol, the "
             "three-population table with Figure 4, the three mechanism evidences with Figure 5, "
             "the dilution arithmetic with the deployment implication, cost and open-set behaviour "
             "with Figures 10 and 11, and the conclusion with boundaries and next steps. Every "
             "slide carries Chinese speaker notes, and every number is read from the result files. "
             "The work followed the pptx-win skill: design system chosen first (ink/paper/blue/"
             "amber palette, 28/16/14/12/11pt rhythm, title-thesis + process + matrix + evidence + "
             "summary patterns), then static OOXML validation (all validations passed) and the "
             "skill's metadata and text-risk reports. Rendered inspection was not possible in this "
             "session: the Office COM preflight refuses a non-active desktop session and no "
             "LibreOffice is installed, so visual QA is replaced by scripts/check_deck_fit_v1.py - "
             "an estimated-glyph layout of all 103 text frames plus slide-bounds and overlap "
             "checks, which first caught a heading that would have wrapped onto the block below it "
             "on slide 7. That check joins the gate (47 checks) and the deck ships under "
             "10_论文介绍与汇报 (143 files, 9.23 MB). One look in PowerPoint is still worth it. "
             "PREVIOUS: wrote 向老师汇报要点.md/.docx: how to present the paper to a supervisor. It carries "
             "a 30-second version, a three-minute version (problem, method, results, why the "
             "verdict flips with scale, the side findings), an eight-slide order for a ten-minute "
             "talk, a one-page number sheet keyed to the supplementary items that hold each "
             "figure, the eight questions most likely to follow with prepared answers - including "
             "'can you call a null result a contribution?' and 'why is the full corpus worse?' - "
             "and a wording red line: no 'first to', no calling the full-corpus deficit "
             "significant when it is still equivalent at 0.01, no production-readiness claim, and "
             "no accuracy-brag when the paper's point is that accuracy misleads. Every number is "
             "read from the result files. The Word edition is built by "
             "build_restructured_manuscript_v4.py --only talk, the freshness and numbering checks "
             "cover it, and it ships under 10_论文介绍与汇报 (142 files, 8.60 MB). Gate 46 checks "
             "green. "
             "PREVIOUS: data-accuracy pass at the class level, the one layer the released-evidence audit "
             "did not cover - it recomputes accuracy and Macro-F1, so the per-class tables and the "
             "normalised confusion matrices had only ever been compared with themselves, while "
             "the manuscript quotes several of their cells. "
             "scripts/audit_per_class_metrics_v1.py now recomputes every per-class precision, "
             "recall and F1 from the released predictions and compares them with the stored "
             "reports: 11 runs (CIC natural for RCCF and the equal forest over three seeds each, "
             "NSL-KDD over three, UNSW-NB15 over the two seeds whose reports exist) and the "
             "normalised matrices where they exist - 270 values, all matching. The nine "
             "class-level values the manuscript prints also reproduce exactly: NSL-KDD R2L recall "
             "0.106 / F1 0.191 and U2R 0.035 / 0.064, UNSW-NB15 Analysis 0.015, Backdoor 0.067, "
             "DoS 0.261, Generic 0.981, Normal 0.805. The audit joins the gate (46 checks) and "
             "reads those nine claims out of the manuscript, so an edited claim fails. "
             "PREVIOUS: generated 论文介绍.md/.docx: a two-page introduction for an advisor or a "
             "collaborator who does not have the manuscript in front of them. Eight sections - "
             "one-sentence conclusion, problem and gap, protocol and corpora, results (the three "
             "populations, the mechanism, cost and open-set behaviour, the external benchmarks), "
             "contributions, honest boundaries, reproducibility, and a BibTeX entry. Every number "
             "is read from the result files: the first draft printed nan twice in the scale row "
             "because the scale summary does not carry per-model Macro-F1 (it now reads the two "
             "aggregate files) and hard-coded the cost multiple (it now divides the training times "
             "from the ten-seed table). The open-set lower bound is truncated rather than rounded "
             "so the introduction prints 0.643 to 0.694, exactly as Section 5.6 does. The Word "
             "edition is built by build_restructured_manuscript_v4.py --only intro, the freshness "
             "and numbering checks cover it, and it ships in the package as 10_论文介绍 (140 "
             "files, 8.56 MB). Gate 45 checks green. "
             "PREVIOUS: materials tidy-up. A check of what the repository still carried found 31 leftovers, "
             "and scripts/quarantine_unrelated_material_v2.py moved all of them out without "
             "deleting anything. Twenty-four were tracked and are now removed from the release: "
             "the six early manuscript versions and three other drafts from 2026-09-02 to 09-05 "
             "(they had been committed on 2026-09-16 in cc70c52, six of them 0.3-0.9 MB each), "
             "three scratch files at the repository root (search_result.json with 1,922 lines of "
             "search-engine output, translate_papers.py, tmp_patch_probe.txt), the eleven "
             "results_*.err run logs the first pass missed - it had only covered .log - and the "
             "two three-line UNSW-NB15 fixtures under tmp_test_unsw/ that no code referenced "
             "(the directory is gone). Seven further files were local only and moved out of the "
             "working root: the session-repair scripts and their logs. Tracked files went to "
             ".quarantine/unrelated_material/ and local ones to .quarantine/local_material/, each "
             "recorded with size and SHA-256 in superseded/unrelated_material_manifest_v2.json, "
             "so every removal is recoverable. "
             "check_release_hygiene_v1.py now forbids the new names and .err logs and verifies "
             "that every quarantined file is where the manifest says it is. Link hygiene checked "
             "at the same time: the UNB CIC page, the UNSW-NB15 project page and the UCI N-BaIoT "
             "dataset all answer 200; github.com cannot be reached from this shell at all (the "
             "connection is refused for any GitHub URL), so the repository itself is verified "
             "through git push and the release tag instead. Gate 45 checks green. "
             "PREVIOUS: the work log gained a Word edition. It moved beside the other deliverables in "
             "重构版论文_v4_20260915/, the builder grew a 'worklog' job (so "
             "build_restructured_manuscript_v4.py --only all regenerates it with the rest), the "
             "DOCX freshness check now requires it to carry the current guard count and round "
             "ledger, and the numbering check covers its numbered list. A new section 八 records "
             "the fixed seven-step operating procedure each round follows: status check, one "
             "rotation item, evidence-backed fix written as an assertion-anchored script, "
             "artefact rebuild, gate, release, and the reporting rule. The log is 225 lines and "
             "travels in the package as both Markdown and Word under 06_研究与写作方案 (138 "
             "files, 8.52 MB). Gate 45 checks green. "
             "PREVIOUS: generated 工作日志_论文项目.md, and made every section of it derived rather than "
             "typed: the round ledger is read from the review report's own headings (rounds 2-19, "
             "reproduced verbatim after a first attempt tried to split dates from themes and "
             "produced a column of dashes) plus all 60 round-labelled commits with their dates; "
             "the guard list is parsed from the gate's check table (45 entries); the status table "
             "comes from check_deliverable_counts_v1.measure(); the data baseline is the output of "
             "the authenticity check; and the open items come from the readiness check. "
             "scripts/build_work_log_v1.py regenerates it in about fifteen seconds, so it cannot "
             "go stale silently, and the log now travels inside the submission package under "
             "06_研究与写作方案 (137 files, 8.48 MB in total). "
             "PREVIOUS: second packaging pass, on the exports themselves rather than the manuscripts. Two "
             "things. (1) The exported table CSVs had never been compared back to the manuscript "
             "they were parsed from - the gate verified the manuscript cells against the result "
             "files, but not the files handed to a production editor. "
             "scripts/check_submission_bundle_v1.py now parses the manuscript tables and requires "
             "each packaged CSV to equal them cell for cell (nine files); all nine already "
             "matched. (2) The slug builder truncated captions mechanically, so Table 7 shipped "
             "as 'table7_the_cic_ids2017_scale_ladder_the.csv'; it now cuts the caption at its "
             "first colon and drops leading and trailing filler words, giving "
             "table7_cic_ids2017_scale_ladder.csv. The same check also rejects archive entry "
             "names carrying characters that some systems refuse and any duplicate entry: 138 "
             "entries, none with reserved characters, no duplicates. The archive is rebuilt "
             "(136 files, 8.47 MB) and the desktop copy refreshed. Gate 45 checks green. "
             "PREVIOUS: full packaging pass. Three gaps closed. (1) The archive carried no separate table "
             "files, which a production editor usually wants: scripts/export_manuscript_tables_v1.py "
             "now parses the eight numbered tables out of the English manuscript into nine CSVs "
             "(Table 4 has two panels) with an index, and they ship as 08_主表. (2) The title, "
             "abstract and keywords were only inside the Word files, so "
             "scripts/export_submission_text_v1.py writes them as plain text for the submission "
             "form (09_投稿文本, with the word and keyword counts recorded at the top). (3) The "
             "archive's own README still said the review report covers 第一至第十一轮 and its "
             "author checklist did not name the CITATION.cff field; the range is now derived from "
             "the report's headings and the checklist names all eight author-input locations. The "
             "archive grows from 124 to 136 files and now holds nine folders. "
             "scripts/check_submission_bundle_v1.py joins the gate (45 checks) and verifies the "
             "archive's own checksum list, its structure, that the supplementary copy inside it "
             "equals the canonical bundle (78 files), and that every packaged document matches "
             "the working tree byte for byte - the staleness that no other check could see. "
             "Rebuild the archive before running the gate whenever the manuscripts change. "
             "PREVIOUS: submission-readiness pass. The JISA hard limits all hold - abstract 249 of 250 "
             "words, seven keywords, five Highlights with the longest at 84 characters, equations "
             "(1)-(5) in order, graphical abstract 3300x2280 - and the content side is complete "
             "(44 gate checks). The open items are the eight places that need author input, and "
             "one of them was not declared anywhere: CITATION.cff still carries 'name: Author to "
             "be completed', while the self-check table named only the manuscript CRediT "
             "placeholder (A5) and the cover-letter signature block (F9). Row A5 and the "
             "author-action list now name the CFF field too. The same pass found row E10 quoting "
             "the longest Highlight as 83 characters when it is 84 (inside the 85 limit either "
             "way). scripts/check_submission_readiness_v1.py joins the gate (44 checks): it "
             "re-derives the JISA limits from the format checker and requires every remaining "
             "placeholder to be named by a 部分通过 row, so an author input can never be silently "
             "missing from the inventory. "
             "PREVIOUS: authenticity and completeness pass over the data the study rests on; no defect was "
             "found, so the round produced a new guard instead. Recorded digests: the eight "
             "CIC-IDS2017 SHA-256 values in supplementary S01 all match the raw CSVs on disk, and "
             "their rows sum to 2,830,743, exactly the source_rows the audit record declares; "
             "NSL-KDD KDDTrain+/KDDTest+ match (19,109,424 and 3,441,513 bytes); UNSW-NB15 "
             "training/testing match (175,341 and 82,332 rows, the published split); and the "
             "N-BaIoT archive matches byte for byte (1,772,922,927 bytes) and extracts to the "
             "recorded nine device folders. Completeness: of 27 per-seed metric files, nine carry "
             "the full ten-seed set and seventeen the three-seed set, plus one single-seed file "
             "from an intermediate MLP run that neither the paper nor the bundle cites; and every "
             "released per-row prediction file covers its population's entire declared test set "
             "(16 populations sampled, zero mismatches). scripts/audit_data_authenticity_v1.py "
             "joins the gate (43 checks) and repeats all of it, skipping the digest section "
             "wherever a raw dataset is absent, since the archives are not redistributed. "
             "PREVIOUS: finer-grained pass over the paths the deliverables cite. Every backticked file "
             "name in the four current-state deliverables (self-check table, README, DATA_CARD, "
             "MODEL_CARD) was resolved against the repository: 44 cited paths, one of which does "
             "not exist - self-check row C1 offered 'final_config.json' as its evidence for "
             "method reproducibility, and no such file is present anywhere (two retired runners "
             "used to write it). The configuration that ships is "
             "results_gate_tuning_v5/selected_gate_config.json, registered as S16 with the "
             "108-configuration search that produced it, so C1 now cites that. "
             "scripts/check_cited_paths_v1.py joins the gate and requires every cited path to "
             "exist; the four dated snapshots (review report, gap audit, P0/P1 manual, structure "
             "plan) are excluded on purpose because they record what was planned on a particular "
             "date and name scripts later built under other names. The same sweep found that all "
             "three snapshots described the review report as covering '第一至第十一轮' while its "
             "own headings run to 第十九轮; the range is now recomputed from those headings by "
             "check_deliverable_counts_v1.py and rewritten to 第一至第十九轮. Gate 42 checks "
             "green; docx, manifest, bundle and desktop rebuilt. "
             "PREVIOUS: main-table pass. Tables 4, 5 and 7 carry the main result and were the last tables "
             "whose cells had never been re-derived, so scripts/audit_main_tables_v1.py now "
             "re-derives all 137 of them from the released runs: Table 4(a) from "
             "results_seeds10_v5 plus the MLP files, 4(b) from the balanced-control runs, Table "
             "5 from the power, effect-size and sign-flip files, and Table 7 from the scale "
             "ladder and the full-corpus summary. The first pass found the Train (s) column of "
             "Table 4(b) printing 0.451 / 0.299 / 0.494 for the three forest rows while "
             "results_cic_balanced_baselines_v3b gives 0.249586 / 0.235422 / 0.130834 for the "
             "same models over the same seeds. No artefact in the repository contains the "
             "printed values - not the per-seed file, not the aggregate, not an earlier balanced "
             "run - and they are not a constant multiple of the released times (1.8x, 1.3x, "
             "3.8x), so they are not a machine-speed difference. Every other cell of those rows "
             "reproduces the released run exactly, as do the conditional-mechanism row (9.130 s) "
             "and the XGBoost row (0.398 s). scripts/fix_table4_balanced_train_times_v1.py "
             "asserts the three source means, rewrites the cells to 0.250 / 0.235 / 0.131 in "
             "both manuscripts and then requires the audit to pass; the audit joins the gate "
             "(41 checks) and README's count is recomputed by the deliverable-counts guard. Also "
             "verified this round: every per-row prediction behind the released runs is tracked "
             "in the public repository (722 files, including the ten 50 MB full-corpus ones), so "
             "the availability statement holds. "
             "PREVIOUS: front-matter pass. The cover letter claimed 'A 118-test suite runs in continuous "
             "integration' while the suite collects 138. The front-matter check could not see it "
             "for two reasons, both now closed in check_aux_documents_v13.py: it compared the "
             "auxiliary documents against the whole manuscript, so reference page ranges "
             "(1189-1232, 1157-1182) vouched for any three-digit number; and its token patterns "
             "matched only decimals and integers of four digits or more, so suite sizes, "
             "search-grid sizes and table counts were never compared at all. The comparison now "
             "uses the body without the reference list and requires every three-digit integer to "
             "appear there - it flagged the 118 immediately - and the suite size is additionally "
             "recomputed from pytest collection by check_deliverable_counts_v1.py, which now "
             "covers the cover letter as well. Fixed by fix_deliverable_counts_v1.py to 138. The "
             "rest of the cover letter was verified against source this round and reproduces: "
             "N-BaIoT 180,000 flows (three 60,000-row classes in dataset_summary.csv), the "
             "53,237 of 2,668,729 physically valid records (data_processing_audit.json), the "
             "7.8x scale-up, the 4.1x model size and 4.6x throughput, the 175x training penalty, "
             "and both TOST verdicts. The old note about the earlier deliverable-count sweep is "
             "kept below. "
             "PREVIOUS: global sweep for statements the deliverables make about themselves. Nine had "
             "drifted, all invisible to the existing gate because nothing recomputed them: the "
             "self-check table still said 118 unit tests (138 collect), 12,761 English words and "
             "35,338 Chinese characters (14,563 and 39,816), 507 numeric tokens per manuscript "
             "(589), and 7 main tables (8 captions, Table 1-8); README announced a 34-check gate "
             "(39 before this round, 40 after it); and the three working documents that open "
             "with a snapshot of the current state - the gap audit, the P0/P1 manual and the "
             "structure plan - still quoted the pre-Round-18 totals of 66 checks with 62 passing "
             "instead of 69 with 65. The gap audit's S8 status line also still described the "
             "English manuscript as 10,800 words with 10 tables. "
             "scripts/check_deliverable_counts_v1.py recomputes all nine from the artefacts "
             "(pytest collection, the gate table, the manuscripts, the figures directory and the "
             "self-check status counts) and fails if a deliverable states a different number; "
             "scripts/fix_deliverable_counts_v1.py re-measures through that check, rewrites the "
             "declarations and then requires the check to pass. The guard joins the gate, which "
             "is why README now says 40 rather than 39. Gate 40 checks green; docx, manifest, "
             "bundle and desktop rebuilt."),
    "timestamp": "2026-09-25T05:10:00+08:00",
}


def main() -> int:
    COUNTER.parent.mkdir(parents=True, exist_ok=True)
    text = COUNTER.read_text(encoding="utf-8") if COUNTER.exists() else ""
    existing: dict[str, str] = {}
    for line in text.splitlines():
        if "=" in line and not line.startswith(" "):
            key, value = line.split("=", 1)
            existing[key] = value
    existing.update(FIELDS)
    order = ["round", "last_item", "last_item_title", "last_result", "note", "timestamp"]
    COUNTER.write_text("\n".join(f"{key}={existing[key]}" for key in order) + "\n",
                       encoding="utf-8")
    for key in order:
        print(f"{key}={existing[key][:90]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
